name 'wirbelsturm-zookeeper'
version '1.0.0'
source 'https://github.com/miguno/puppet-zookeeper.git'
author 'Michael G. Noll'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring ZooKeeper'
description 'Module for managing and configuring ZooKeeper'
project_page 'https://github.com/miguno/puppet-zookeeper'
#DISABLED UNTIL PUBLISHED ON PUPPETFORGE#dependency 'miguno/puppet-supervisor'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
